# Generated by Django 4.0.5 on 2023-02-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, upload_to='noticias/img')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(null=True)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
