# Generated by Django 4.0.5 on 2023-02-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, upload_to='beleza/img')),
                ('nome', models.CharField(help_text='O nome do curso aparecerá como opção para o aluno.', max_length=200, null=True, verbose_name='DIGITE O NOME DO CURSO:')),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beleza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='NOME COMPLETO:')),
                ('CPF', models.CharField(help_text='Coloque os . e os - : Ex: 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='DIGITE O SEU CPF:')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=50, null=True, verbose_name='INFORME SEU SEXO:')),
                ('nascimento', models.CharField(help_text='Coloque as / : Ex: 00/00/0000', max_length=10, null=True, verbose_name='INFORME SUA DATA DE NASCIMENTO:')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='INFORME SEU E-MAIL:')),
                ('celular', models.CharField(help_text='Coloque o DDD em ( ) : Ex: (31)9999-9999', max_length=14, null=True, verbose_name='DIGITE O NÚMERO DO SEU CELULAR:')),
                ('cep', models.CharField(max_length=9, null=True, verbose_name='INFORME SEU CEP')),
                ('estado', models.CharField(choices=[('ACRE', 'AC'), ('ALAGOAS', 'AL'), ('AMAPÁ', 'AP'), ('AMAZONAS', 'AM'), ('BAHIA', 'BA'), ('CEARÁ', 'CE'), ('DISTRITO FEDERAL', 'DF'), ('ESPÍRITO SANTO', 'ES'), ('GOIÁS', 'GO'), ('MARANHÃO', 'MA'), ('MATO GROSSO', 'MT'), ('MATO GROSSO DO SUL', 'MS'), ('MINAS GERAIS', 'MG'), ('PARÁ', 'PA'), ('PARAÍBA', 'PB'), ('PARANÁ', 'PR'), ('PERNAMBUCO', 'PE'), ('PIAUÍ', 'PI'), ('RIO DE JANEIRO', 'RJ'), ('RIO GRANDE DO NORTE', 'RN'), ('RIO GRANDE DO SUL', 'RS'), ('RONDÔNIA', 'RO'), ('RORÔIMA', 'RR'), ('SANTA CATARINA', 'SC'), ('SÃO PAULO', 'SP'), ('SERGIPE', 'SE'), ('TOCÂNTIS', 'TO')], max_length=200, null=True, verbose_name='UF:')),
                ('cidade', models.CharField(max_length=100, null=True, verbose_name='MUNICIPIO')),
                ('bairro', models.CharField(max_length=200, null=True, verbose_name='BAIRRO:')),
                ('rua', models.CharField(max_length=200, null=True, verbose_name='RUA:')),
                ('numero', models.IntegerField(null=True, verbose_name='N°:')),
                ('complemento', models.CharField(max_length=30, null=True, verbose_name='COMPLEMENTO:')),
                ('pcd', models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], max_length=3, null=True, verbose_name='INFORME SE VOCÊ É PCD:')),
                ('IdCurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beleza.curso', verbose_name='ESCOLHA O CURSO QUE VOCÊ DESEJA CURSAR')),
            ],
        ),
    ]
