# Generated by Django 4.0.5 on 2023-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='CPF',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='pcd',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='teste',
            name='nome',
            field=models.CharField(max_length=14),
        ),
    ]
