# Generated by Django 4.0.5 on 2023-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_teste_cpf_remove_teste_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
