# Generated by Django 4.0.5 on 2023-02-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_teste_data_teste_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=50, null=True),
        ),
    ]
