# Generated by Django 4.0.5 on 2023-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_teste_alter_inscricao_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, upload_to='teste/img')),
                ('nome', models.CharField(max_length=200)),
                ('CPF', models.CharField(max_length=14, null=True)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=50, null=True)),
            ],
        ),
    ]
