# Generated by Django 4.0.5 on 2023-02-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_teste_bairro_teste_celular_teste_cep_teste_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='pcd',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='rua',
        ),
    ]
