# Generated by Django 4.0.5 on 2023-02-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_teste_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teste',
            new_name='Matricula',
        ),
    ]
