# Generated by Django 4.0.5 on 2023-02-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_teste_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='celular',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cep',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='CPF',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
