# Generated by Django 4.0.5 on 2023-02-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_matricula_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='cidade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='numero',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rua',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
