# Generated by Django 4.0.5 on 2023-02-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_matricula_cidade_matricula_numero_matricula_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='bairro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='complemento',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='pcd',
            field=models.CharField(choices=[('SIM', 'sim'), ('NÃO', 'Não')], max_length=3, null=True),
        ),
    ]
