# Generated by Django 4.0.5 on 2023-02-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_matricula_bairro_matricula_complemento_matricula_pcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='pcd',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='rua',
        ),
    ]
