# Generated by Django 4.0.5 on 2023-02-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_matricula_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='bairro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
