# Generated by Django 4.0.5 on 2023-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_matricula_bairro_matricula_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
