# Generated by Django 4.0.5 on 2023-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_matricula_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='rua',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
