# Generated by Django 4.0.5 on 2023-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_inscricao_pcd_alter_matricula_pcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
