# Generated by Django 4.0.5 on 2023-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_matricula_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='nascimento',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
