# Generated by Django 4.0.5 on 2023-02-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_matricula_nascimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
