# Generated by Django 4.0.5 on 2023-02-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_delete_inscricao_delete_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
