# Generated by Django 4.0.5 on 2023-02-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CPF',
            field=models.CharField(help_text='Coloque os . e os - : Ex: 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='DIGITE O SEU CPF:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='celular',
            field=models.CharField(help_text='Coloque o DDD em () : Ex: (31)99999-9999', max_length=14, null=True, verbose_name='DIGITE O NÚMERO DO SEU CELULAR:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nascimento',
            field=models.CharField(help_text='Coloque as / : Ex: 00/00/0000', max_length=10, null=True, verbose_name='INFORME SUA DATA DE NASCIMENTO:'),
        ),
    ]
