# Generated by Django 4.0.5 on 2023-02-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_cpf_alter_customer_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CPF',
            field=models.CharField(help_text='Coloque os . e os - : Ex: 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='DIGITE O SEU CPF:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bairro',
            field=models.CharField(max_length=200, null=True, verbose_name='BAIRRO:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='celular',
            field=models.CharField(help_text='Coloque o DDD em ( ) : Ex: (31)9999-9999', max_length=14, null=True, verbose_name='DIGITE O NÚMERO DO SEU CELULAR:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cep',
            field=models.CharField(max_length=9, null=True, verbose_name='INFORME SEU CEP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cidade',
            field=models.CharField(max_length=100, null=True, verbose_name='MUNICIPIO'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='complemento',
            field=models.CharField(max_length=30, null=True, verbose_name='COMPLEMENTO:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='INFORME SEU E-MAIL:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='estado',
            field=models.CharField(choices=[('ACRE', 'AC'), ('ALAGOAS', 'AL'), ('AMAPÁ', 'AP'), ('AMAZONAS', 'AM'), ('BAHIA', 'BA'), ('CEARÁ', 'CE'), ('DISTRITO FEDERAL', 'DF'), ('ESPÍRITO SANTO', 'ES'), ('GOIÁS', 'GO'), ('MARANHÃO', 'MA'), ('MATO GROSSO', 'MT'), ('MATO GROSSO DO SUL', 'MS'), ('MINAS GERAIS', 'MG'), ('PARÁ', 'PA'), ('PARAÍBA', 'PB'), ('PARANÁ', 'PR'), ('PERNAMBUCO', 'PE'), ('PIAUÍ', 'PI'), ('RIO DE JANEIRO', 'RJ'), ('RIO GRANDE DO NORTE', 'RN'), ('RIO GRANDE DO SUL', 'RS'), ('RONDÔNIA', 'RO'), ('RORÔIMA', 'RR'), ('SANTA CATARINA', 'SC'), ('SÃO PAULO', 'SP'), ('SERGIPE', 'SE'), ('TOCÂNTIS', 'TO')], max_length=200, null=True, verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nascimento',
            field=models.CharField(help_text='Coloque as / : Ex: 00/00/0000', max_length=10, null=True, verbose_name='INFORME SUA DATA DE NASCIMENTO:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='NOME COMPLETO:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='N°:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pcd',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], max_length=3, null=True, verbose_name='INFORME SE VOCÊ É PCD:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rua',
            field=models.CharField(max_length=200, null=True, verbose_name='RUA:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=50, null=True, verbose_name='INFORME SEU SEXO:'),
        ),
    ]
