# Generated by Django 4.0.5 on 2023-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_cpf_alter_customer_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='curso',
            field=models.CharField(choices=[('INFORMÁTICA', 'Informática'), ('TELEMARKTING', 'Telemarkting'), ('COSTURA', 'Costura'), ('ELÉTRICA', 'Elétrica'), ('ADMINISTRATIVO', 'Administrativo'), ('SECRETARIADO', 'Secretariado')], max_length=200, null=True, verbose_name='ESCOLHE O CURSO QUE VOCÊ DESEJA INSCREVER:'),
        ),
    ]
