# Generated by Django 4.0.5 on 2023-02-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissionalizante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, upload_to='profissionalizante/img')),
                ('nome', models.CharField(help_text='O nome do curso aparecerá como opção para o aluno.', max_length=200, null=True, verbose_name='DIGITE O NOME DO CURSO:')),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='curso',
        ),
        migrations.AddField(
            model_name='customer',
            name='IdProfissionalizante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.profissionalizante', verbose_name='ESCOLHA O CURSO QUE VOCÊ DESEJA CURSAR'),
        ),
    ]
